package com.cleo.prototype;

public class Constants {
    public static final String BASE_URL = "https://1gu2ncvsx9.execute-api.us-west-2.amazonaws.com/PR162";
    public static final String AUTH_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6IjQ3WUdZTDlLOE05ME0zU05POVlQSUQ1WEkiLCJzdHQiOiJhY2Nlc3MifQ.eyJqdGkiOiIyYlNIZm9EcDdaTzd6bWxjdjZwZEVqIiwiaWF0IjoxNTAwNTc4MzYxLCJpc3MiOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2FwcGxpY2F0aW9ucy8zYkRLQzV4TWVHemNIZllWT2xJYnVnIiwic3ViIjoiaHR0cHM6Ly9hcGkuc3Rvcm1wYXRoLmNvbS92MS9hY2NvdW50cy80UFFwZ0lKYmFoSmJNVHpyVUJjSnFjIiwiZXhwIjoxNTAwNjY0NzYxLCJzY29wZSI6IntcImlkXCI6XCI0UFFwZ0lKYmFoSmJNVHpyVUJjSnFjXCIsXCJlbWFpbFwiOlwicmtyaWVyQGNsZW8uY29tXCIsXCJnaXZlbk5hbWVcIjpcIkJvYlwiLFwic3VybmFtZVwiOlwiS3JpZXJcIixcImNvbXBhbnlcIjpcImNsZW9cIixcIm9yZ0lkXCI6XCIzd1BhMUZlaDZBUzh1N0dwU093ZEtBXCJ9In0.EJnXzWi3tGdYzzYL1j_bRpzC95JwIExW8cyM5mtVUUw";

    private Constants() {
    }

}
